# Generated by Django 4.1.6 on 2023-02-06 23:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_image_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date of create'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date of update'),
        ),
    ]
